POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8000/1/comment

###

POST http://localhost:8000/1/comment
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NDg5ODMsInN1YiI6ImFjY2VzcyJ9.bCKxXwNb8pIss20FsvnqYbMSL7Lh9eOApxukCy4JY3Y

{
    "text": "Новый коммент 3"
}

###

PUT http://localhost:8000/1/comment/14
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NDg5ODMsInN1YiI6ImFjY2VzcyJ9.bCKxXwNb8pIss20FsvnqYbMSL7Lh9eOApxukCy4JY3Y

{
    "text": "cool"
}

###

DELETE http://localhost:8000/1/comment/17
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NDgzODIsInN1YiI6ImFjY2VzcyJ9.gxgUyf2L1XdYXprNgF0n0MEJ2PUrunU9rAS2fP_ZAoY

###

GET http://localhost:8000/group

###

GET http://localhost:8000/group/5/posts

###

POST http://localhost:8000/group
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NTUwMDEsInN1YiI6ImFjY2VzcyJ9.SoVh1UAApXBWgml6ADxPVVki86sJSn6wztuAteVAblo

{
    "title": "Group 3"
}

###

PUT http://localhost:8000/group/5
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NTUwMDEsInN1YiI6ImFjY2VzcyJ9.SoVh1UAApXBWgml6ADxPVVki86sJSn6wztuAteVAblo

{
    "title": "California 2"
}

###

DELETE http://localhost:8000/group/4
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NTE2OTIsInN1YiI6ImFjY2VzcyJ9.yxkNHYDS5dK0rAUMaqiGLoKqIUVGNtNQT29YgemlI8s

###

GET http://localhost:8000/post
Content-Type: application/json

###

POST http://localhost:8000/post
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NTUwMDEsInN1YiI6ImFjY2VzcyJ9.SoVh1UAApXBWgml6ADxPVVki86sJSn6wztuAteVAblo

{
    "text": "Otlichnij deni progulki 0000",
    "image": "string 111",
    "group_id": 5
}

###

PUT http://localhost:8000/post/6
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NTUwMDEsInN1YiI6ImFjY2VzcyJ9.SoVh1UAApXBWgml6ADxPVVki86sJSn6wztuAteVAblo

{
    "text": "Otlichnij deni progulki123",
    "image": "string123"
}

###

DELETE http://localhost:8000/post/6
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NTUwMDEsInN1YiI6ImFjY2VzcyJ9.SoVh1UAApXBWgml6ADxPVVki86sJSn6wztuAteVAblo

###
