POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8000/1/comment

###

POST http://localhost:8000/comment
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NDMzMzQsInN1YiI6ImFjY2VzcyJ9.XeX7S_D_lHPICbfP2bqQCEAxmvtmZg1zsi0N-kye9JY

{
    "post_id": 1,
    "text": "string555500111",
    "created": "2021-05-25T10:15:45.225Z"
}

###

PUT http://localhost:8000/comment/1
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NDgzODIsInN1YiI6ImFjY2VzcyJ9.gxgUyf2L1XdYXprNgF0n0MEJ2PUrunU9rAS2fP_ZAoY

{
    "post_id": 1,
    "text": "string111"
}

###

DELETE http://localhost:8000/comment/3
Content-Type: application/json
Authorization: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MjE5NDgzODIsInN1YiI6ImFjY2VzcyJ9.gxgUyf2L1XdYXprNgF0n0MEJ2PUrunU9rAS2fP_ZAoY

###
